Enable crosvm linux_musl_arm64 build
Having crosvm disabled for linux_musl_arm64 causes a dependency error
when building for linux_musl_arm64:
error: device/google/cuttlefish/build/Android.bp:208:1: module "cvd-host_package" variant "linux_musl_arm64": depends on disabled module "crosvm"

Bug: 236052820
Test: build crosvm for linux_musl_arm64
Change-Id: I876d09657a81c8313da92855c3f7b26a33078892