[DO-NOT-MERGE] Break protected mode to test CI
This should generate the following error when running in --protected-vm
mode on Aarch64:

    [ERROR:external/crosvm/src/main.rs:2779] crosvm has exited with
    error: the architecture failed to build the vm: this function isn't
    supported

So that this CL should fail Presubmit-Verified iff it is actually tested
on a physical device.

Test: -
Bug: 223769777
Change-Id: Icc4f5e4e75fc245c7756d79eeca1620ac978da96