Update patch set 1
Patch Set 1:

I think this change caused the following build error:
error: external/crosvm/x86_64/Android.bp:32:1: module "libhost_cpuid" variant
"linux_glibc_x86_64_static": module source path 
"external/crosvm/x86_64/host_cpuid.c" does not exist
Could you verify/fix the error? Thanks.

Patch-set: 1
CC: Gerrit User 1052399 <1052399@85c56323-6fa9-3386-8a01-6480fb634889>