DO NOT SUBMIT, to test protobuf-codegen for protos
* To generate cdisk_spec.rs and plugin.rs and include them.
* Use include!(concat!(env!("OUT_DIR"), "/cdisk_spec.rs"));
  instead of symlinks.
* Can include ${OUT_DIR}/cdisk_spec.rs, but
  has the following errors that do not happen with symlinks:
    error: an inner attribute is not permitted in this context
    error: an inner attribute is not permitted following an outer attribute

Test: make
Change-Id: I00282a09dc8b1b9d7d4b1f729c025bd76754b353